### PR TITLE
First refresh of IATI Registry homepage

### PR DESCRIPTION
**Pull request by stevieflow**
@amercader any chance to push the to staging, so I can review it (and work on subsequent pages)?

### CODE REVIEW

**Comment by amercader** [comment]
@stevieflow Done.

http://iati2.staging.ckanhosted.com/

We need to update links to /datastore, /tools and /dashboard

**Comment by stevieflow** [comment]
That's great, thanks @amercader 

Yes - I will create the new pages next week, alongside updating others

I may also want to nest some pages as sub-pages of others (a bit like the "data" drop-down).

**Comment by amercader** [comment]
@stevieflow No problem, dropdowns can be easily defined like this:

```html

<li>
  <a href="/">Header menu item</a>
  <ul class="dropdown">
    <li><a href="/subitem1">Dropdown item 1</a></li>
    <li><a href="/subitem2">Dropdown item 2</a></li>
    <li><a href="/subitem3">Dropdown item 3</a></li>
  </ul>
</li>
```

**Comment by stevieflow** [comment]
Great.  To which file should I add that btw?

**Comment by amercader** [comment]
https://github.com/okfn/ckanext-iati/blob/master/ckanext/iati/theme/templates/header.html

**Pull request merged**
